env:
  global:
  - CC_TEST_REPORTER_ID=7288d4a38203cc17d30f9fb4e9d46399d6e7b6f017572bc833d8da3f38fea48b
language: ruby
rvm:
- 2.5.1
- 2.3.0
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- gem update --system
- gem install bundler
script:
  - bundle exec rspec
after_script:
- ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
cache: bundler